import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar/NavBar";
import Footer from "./_components/Footer/Footer";
import SessionWrapper from "./_components/SessionWrapper/SessionWrapper";
import SearchResultProvider from "./_context/SearchResult/SearchResult";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CyberVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white overflow-x-hidden">
        <SearchResultProvider>
        <SessionWrapper>
          <NavBar />
          {children}
          <Footer />
        </SessionWrapper>
        </SearchResultProvider>
      </body>
    </html>
  );
}
